trigger:
  - main

pool:
  name: SelfHosted

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: Backend
        displayName: "Backend CI"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd coffehub/backend
              npm install
              npm test
            displayName: "Install & Test Backend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'coffehub/backend'
              ArtifactName: 'backend'
              publishLocation: 'Container'
            displayName: "Publicar artefacto Backend"

      - job: Frontend
        displayName: "Frontend CI"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd coffehub/frontend
              npm install || true
              npm run build || echo "No build script definido"
            displayName: "Build Frontend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'coffehub/frontend'
              ArtifactName: 'frontend'
              publishLocation: 'Container'
            displayName: "Publicar artefacto Frontend"