trigger:
  - main

pool:
  name: SelfHosted   # usa tu agente self-hosted, o reemplaza por "vmImage: ubuntu-latest" si querés hosted

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      # --------------------- BACKEND ---------------------
      - job: Backend
        displayName: "Backend CI"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd tp5/coffehub/backend
              npm install
            displayName: "Install Backend"

          - script: |
              cd tp5/coffehub/backend
              npm test || echo "No tests definidos (skipped)"
            displayName: "Run Backend Tests (Optional)"
            continueOnError: true

          # Empaquetar backend como .zip
          - task: ArchiveFiles@2
            displayName: "Empaquetar Backend"
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/tp5/coffehub/backend'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'

          # Publicar artefacto backend
          - task: PublishBuildArtifacts@1
            displayName: "Publicar artefacto Backend"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
              ArtifactName: 'backend'
              publishLocation: 'Container'

      # --------------------- FRONTEND ---------------------
      - job: Frontend
        displayName: "Frontend CI"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd tp5/coffehub/frontend
              npm install || true
              npm run build || echo "No build script definido"
            displayName: "Build Frontend"

          # Empaquetar frontend como .zip
          - task: ArchiveFiles@2
            displayName: "Empaquetar Frontend"
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/tp5/coffehub/frontend'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'

          # Publicar artefacto frontend
          - task: PublishBuildArtifacts@1
            displayName: "Publicar artefacto Frontend"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend.zip'
              ArtifactName: 'frontend'
              publishLocation: 'Container'
