trigger:
  - main

pool:
  name: SelfHosted

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: Backend
        displayName: "Backend CI"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd tp5/coffehub/backend
              npm install
            displayName: "Install Backend"

          - script: |
              cd tp5/coffehub/backend
              npm test || echo "Tests skipped (no DB available)"
            displayName: "Run Backend Tests (Optional)"
            continueOnError: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'tp5/coffehub/backend'
              ArtifactName: 'backend'
              publishLocation: 'Container'
            displayName: "Publicar artefacto Backend"

      - job: Frontend
        displayName: "Frontend CI"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd tp5/coffehub/frontend
              npm install || true
              npm run build || echo "No build script definido"
            displayName: "Build Frontend"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'tp5/coffehub/frontend'
              ArtifactName: 'frontend'
              publishLocation: 'Container'
            displayName: "Publicar artefacto Frontend"
